Updated FreeBSD build script. (#11057)
* Updated FreBSD build script.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -123,8 +123,8 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - job_name: FreeBSD 13.2 x64
-            freebsd_version: '13.2'
+          - job_name: FreeBSD 14.4 x64
+            freebsd_version: '14.4'
     name: ${{ matrix.job_name }}
     runs-on: ubuntu-latest
     timeout-minutes: 20  # Should complete in 11 minutes
@@ -132,76 +132,82 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 50
-      - name: Run in VM
-        uses: cross-platform-actions/action@v0.23.0
-        timeout-minutes: 19
+      - name: Start VM
+        uses: cross-platform-actions/action@v1.3.0
         with:
           operating_system: freebsd
-          hypervisor: qemu
           memory: 12G
           cpu_count: 4
           sync_files: runner-to-vm
           version: ${{ matrix.freebsd_version }}
           shell: bash
-          run: |
-            set -uexo pipefail
+      - name: Run in VM
+        timeout-minutes: 19
+        shell: cpa.sh {0}
+        run: |
+          set -uexo pipefail
 
-            freebsd_version='${{ matrix.freebsd_version }}'
-            freebsd_major="${freebsd_version:0:2}"
+          freebsd_version='${{ matrix.freebsd_version }}'
+          freebsd_major="${freebsd_version:0:2}"
 
-            export OS_NAME=freebsd
-            export MODEL=64
-            export HOST_DMD=dmd
-            export N="$(nproc)"
-            export FULL_BUILD=false
-            export CI_DFLAGS="-version=TARGET_FREEBSD${freebsd_major}"
+          export OS_NAME=freebsd
+          export MODEL=64
+          export HOST_DMD=dmd
+          export N="$(nproc)"
+          export FULL_BUILD=false
+          export CI_DFLAGS="-version=TARGET_FREEBSD${freebsd_major}"
 
-            #if [[ "$freebsd_major" == 12 ]]; then
-            #  sudo sed -i '' -e 's|pkg.FreeBSD.org|mirrors.xtom.com/freebsd-pkg|' /etc/pkg/FreeBSD.conf
-            #fi
+          #if [[ "$freebsd_major" == 12 ]]; then
+          #  sudo sed -i '' -e 's|pkg.FreeBSD.org|mirrors.xtom.com/freebsd-pkg|' /etc/pkg/FreeBSD.conf
+          #fi
 
-            bash --version
+          bash --version
 
-            echo '::group::Install git'
-            sudo pkg install -y git
-            echo '::endgroup::'
+          # compiler/test/dshell/dwarf.d needs objdump from binutils.
+          # It will also optionally use llvm-dwarfdump from llvm.
+          # So, this installs both.
+          sudo pkg install -y binutils llvm
 
-            echo '::group::Clone DMD'
-            ref='${{ github.ref }}'
-            if [[ "$ref" =~ ^refs/pull/ ]]; then
-              REPO_BRANCH="$GITHUB_BASE_REF"
-            elif [[ "$ref" =~ ^refs/(heads|tags)/(.*)$ ]]; then
-              REPO_BRANCH="${BASH_REMATCH[2]}"
-            else
-              echo "Error: unexpected GitHub ref '$ref'" >&2
-              exit 1
-            fi
+          echo '::group::Install git'
+          sudo pkg install -y git
+          echo '::endgroup::'
 
-            git clone --branch "$REPO_BRANCH" --depth 1 https://github.com/dlang/dmd.git ../dmd
-            echo '::endgroup::'
+          echo '::group::Clone DMD'
+          ref='${{ github.ref }}'
+          if [[ "$ref" =~ ^refs/pull/ ]]; then
+            REPO_BRANCH="$GITHUB_BASE_REF"
+          elif [[ "$ref" =~ ^refs/(heads|tags)/(.*)$ ]]; then
+            REPO_BRANCH="${BASH_REMATCH[2]}"
+          else
+            echo "Error: unexpected GitHub ref '$ref'" >&2
+            exit 1
+          fi
 
-            cd ../dmd
+          git clone --branch "$REPO_BRANCH" --depth 1 https://github.com/dlang/dmd.git ../dmd
+          echo '::endgroup::'
 
-            echo '::group::Install prerequisites'
-            sudo -E ci/cirrusci.sh
-            echo '::endgroup::'
+          cd ../dmd
 
-            echo '::group::Install host compiler'
-            ci/run.sh install_host_compiler
-            echo '::endgroup::'
+          echo '::group::Install prerequisites'
+          sudo -E ci/cirrusci.sh
+          echo '::endgroup::'
 
-            echo '::group::Build'
-            ci/run.sh build
-            echo '::endgroup::'
+          echo '::group::Install host compiler'
+          ci/run.sh install_host_compiler
+          echo '::endgroup::'
 
-            echo '::group::Test dmd'
-            ci/run.sh test_dmd
-            echo '::endgroup::'
+          echo '::group::Build'
+          ci/run.sh build
+          echo '::endgroup::'
 
-            echo '::group::Test druntime'
-            ci/run.sh test_druntime
-            echo '::endgroup::'
+          echo '::group::Test dmd'
+          ci/run.sh test_dmd
+          echo '::endgroup::'
 
-            echo '::group::Test phobos'
-            ci/run.sh test_phobos
-            echo '::endgroup::'
+          echo '::group::Test druntime'
+          ci/run.sh test_druntime
+          echo '::endgroup::'
+
+          echo '::group::Test phobos'
+          ci/run.sh test_phobos
+          echo '::endgroup::'
